@HOSTNAME = localhost:5044
@PORT = 5044

### add event
POST http://{{HOSTNAME}}/api/add-event
Content-Type: application/json

{
    "name":"lat pull dowm",
    "coordinator":"ChongWen Su",
    "place":"Taipei 101",
    "lat":20.44,
    "lng":130.77,
    "fee":400   
}

### query event
POST http://{{HOSTNAME}}/api/query-event
Content-Type: application/json

{
    "lat":20.42,
    "lng":130.75,
    "length":500
}

### wrong event
GET http://{{HOSTNAME}}/api/wrong