@HOSTNAME = localhost:5044
@PORT = 5044

### add event
GET http://{{HOSTNAME}}/api/add-event


### query event
GET http://{{HOSTNAME}}/api/query-event


### wrong event
GET http://{{HOSTNAME}}/api/wrong